name: build
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go get github.com/gdamore/tcell
      - run: mkdir go
      - run: mkdir go/src
      - run: mkdir go/src/github.com
      - run: mkdir go/src/github.com/bkthomps
      - run: mkdir go/src/github.com/bkthomps/Ven
      - run: cp ven.go go/src/github.com/bkthomps/Ven/ven.go
      - run: cp -r buffer go/src/github.com/bkthomps/Ven/buffer
      - run: cp -r screen go/src/github.com/bkthomps/Ven/screen
      - run: cp -r search go/src/github.com/bkthomps/Ven/search
      - run: go test ./...
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: if [[ $(gofmt -l -d -s -e .) ]]; then exit 1; fi
