name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: go get github.com/bkthomps/Ven
    - run: go get github.com/gdamore/tcell
    - run: go test ./...
