name: build
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: go get github.com/gdamore/tcell
      - run: mkdir /home/runner/go/src/github.com/bkthomps
      - run: mkdir /home/runner/go/src/github.com/bkthomps/Ven
      - run: echo $GOPATH
      - run: cp ven.go /home/runner/go/src/github.com/bkthomps/Ven/ven.go
      - run: cp -r buffer /home/runner/go/src/github.com/bkthomps/Ven/buffer
      - run: cp -r screen /home/runner/go/src/github.com/bkthomps/Ven/screen
      - run: cp -r search /home/runner/go/src/github.com/bkthomps/Ven/search
      - run: go test ./...
  gofmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: if [[ $(gofmt -l -d -s -e .) ]]; then exit 1; fi
