name: build
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: go get -t ./...
    - run: mkdir -p /home/runner/go/src/github.com/bkthomps/Ven
    - run: cp -r $(pwd) /home/runner/go/src/github.com/bkthomps/Ven
    - run: go test ./... -coverprofile=coverage.txt -covermode=atomic
    - uses: codecov/codecov-action@v2
      with:
        file: ./coverage.txt
  gofmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: if [[ $(gofmt -l -d -s -e .) ]]; then exit 1; fi
